# Copyright (c) 2021-2026 Huawei Device Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import argparse
import re
from copy import deepcopy
from pathlib import Path
from typing import List

import dill

from common.enum.common_enum import KernelMemoryReason
from log_manager.slicing.leak.memory_leak.common_log.kernel_header import KernelHeader
from log_manager.slicing.leak.memory_leak.common_log.mem_check_detial_info import MemCheckDetialInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_meminfo import MemCheckMemInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_proc_info import MemCheckProcInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_smaps_info import MemCheckSmapsInfo
from log_manager.slicing.leak.memory_leak.common_log.process_dma_buf_info import ProcessDmaBuf
from tools.file_tools import read_file_to_list


class KernelLeak:

    def __init__(self):
        self.process_name = ''
        self.kernel_header: KernelHeader = KernelHeader()
        self.mem_check_proc_info: MemCheckProcInfo = MemCheckProcInfo()
        self.mem_check_dma_buf_info: ProcessDmaBuf = ProcessDmaBuf()
        self.mem_check_detial_info: MemCheckDetialInfo = MemCheckDetialInfo()
        self.mem_check_smaps_info = MemCheckSmapsInfo()
        self.mem_check_meminfo: MemCheckMemInfo = MemCheckMemInfo()
        self.happen_time = ''
        self.reason = []

    def __str__(self):
        return f'泄露类型：{self.reason}\n' \
               f'时间：{self.happen_time}'

    @staticmethod
    def leak_type_build(context: List[str]):
        leak_type = ''
        memory_name_match = re.compile('memoryName:(?P<leak_type>.*)')
        for line in context:
            match = memory_name_match.match(line)
            if match:
                leak_type = match.group('leak_type').strip()
                break
            if 'Process dma_heap info' in line:
                leak_type = 'ion'
        return leak_type

    @staticmethod
    def log_split(context: List[str]):
        target_index_list = []
        for index, line in enumerate(context):
            if 'Generated by HiviewDFX @OpenHarmony' in line:
                target_index_list.append(index)
        if len(target_index_list) >= 2:
            context = context[target_index_list[-1]:]
        return context

    def build(self, log_path: str):
        match = re.search('memleak-kernel-(?P<process_name>[0-9a-zA-Z_.]+)-0-(?P<happen_time>\d+)', log_path)
        if not match:
            return
        self.process_name = match.group('process_name')
        self.happen_time = match.group('happen_time')
        context = read_file_to_list(Path(log_path))
        leak_type_dict = {'ion': self.ion_leak_build,
                          'ashmem': self.ashmem_leak_build,
                          'gpu': self.gpu_leak_build,
                          'slab': self.slab_leak_build,
                          'kernel_zone': self.kernel_zone_build}
        target_context = self.log_split(context)
        self.reason = self.leak_type_build(target_context)
        if not self.reason:
            pass
        build_methed = leak_type_dict.get(self.reason, None)
        if build_methed:
            context = deepcopy(target_context)
            build_methed(context)
        return self

    def ashmem_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.ASHMEM.value
        self.kernel_header.next_handle(self.mem_check_proc_info)
        self.kernel_header.handle(context)

    def ion_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.ION.value
        self.kernel_header \
            .next_handle(self.mem_check_meminfo) \
            .next_handle(self.mem_check_proc_info) \
            .next_handle(self.mem_check_dma_buf_info)
        self.kernel_header.handle(context)

    def gpu_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.GPU.value
        self.reason.append(KernelMemoryReason.GPU.value)
        self.kernel_header.next_handle(self.mem_check_proc_info)
        self.kernel_header.handle(context)

    def slab_leak_build(self, context: List[str]):
        self.mem_check_proc_info.reason = KernelMemoryReason.SLAB.value
        self.kernel_header.next_handle(self.mem_check_proc_info)
        self.kernel_header.handle(context)

    def kernel_zone_build(self, context: List[str]):
        self.reason.append(KernelMemoryReason.KERNEL_ZONE.value)
        self.kernel_header.next_handle(self.mem_check_smaps_info)
        self.kernel_header.handle(context)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--path", required=True, help="文件路径")
    args = parser.parse_args()
    with open(args.path, 'r', encoding='utf-8', errors='ignore') as file:
        context_ = file.readlines()
        # 存储对象
        kernel_leak = KernelLeak().build(args.path)
        print(kernel_leak.__str__())
        kernel_leak_path = args.path.replace('.txt', ".pkl")
        with open(kernel_leak_path, 'wb') as f:
            dill.dump(kernel_leak, f)
