# Copyright (c) 2021-2026 Huawei Device Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
import argparse
import re

from typing import List
import dill
from common.enum.common_enum import NativeMemoryType
from log_manager.slicing.leak.memory_leak.common_log.mem_check_detial_info import MemCheckDetialInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_meminfo import MemCheckMemInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_sample_nmd_info import MemCheckSampleNmdInfo
from log_manager.slicing.leak.memory_leak.common_log.mem_check_smaps_info import MemCheckSmapsInfo


class NativeLeak:

    def __init__(self):
        self.mem_check_detial_info = MemCheckDetialInfo()
        self.mem_check_smaps_info = MemCheckSmapsInfo()
        self.mem_check_nmd_info = MemCheckSampleNmdInfo()
        self.mem_check_meminfo: MemCheckMemInfo = MemCheckMemInfo()
        self.nmd_set = set()
        self.rate_dict = {}

    def build(self, context: List[str]):
        target_index_list = []
        for index, line in enumerate(context):
            if 'Generated by HiviewDFX @OpenHarmony' in line:
                target_index_list.append(index)
        if len(target_index_list) >= 2:
            context = context[target_index_list[-1]:]
        self.mem_check_meminfo \
            .next_handle(self.mem_check_smaps_info) \
            .next_handle(self.mem_check_detial_info) \
            .next_handle(self.mem_check_nmd_info)
        self.mem_check_meminfo.handle(context)
        return self


def get_rate_info(native_leak: NativeLeak, sample_path: str):
    re_dict = {
        NativeMemoryType.JEMALLOC_LEAK: re.compile(r'\[anon:native_heap:jemalloc]'),
        NativeMemoryType.ASHMEM_LEAK: re.compile(r'anon_inode:dev/ashmem/*'),
        NativeMemoryType.ARKTS_LEAK: re.compile(r'anon:ArkTS\s+Heap'),
        NativeMemoryType.ANON_LEAK: re.compile(r'\[anon]')
    }
    with open(sample_path, 'rb') as f:
        sample_info = dill.load(f)
    pss_dict = {}
    swap_info_list = native_leak.mem_check_smaps_info.swap_info_list
    for mem_type, pattern in re_dict.items():
        leak_total_pss = 0
        swap_list = []
        for swap_info in swap_info_list:
            if pattern.search(swap_info.name):
                leak_total_pss += swap_info.pss + swap_info.swap_pss
                swap_list.append(swap_info)
            if 'libmemtracker.so' in swap_info.name:
                raise Exception('非问题，机器预置memtracker工具')
        pss_dict[mem_type] = {'rate': float(leak_total_pss) / sample_info.total_pss,
                              'pss': leak_total_pss,
                              'swap_list': swap_list}
    sorted_pss_dict = sorted(pss_dict.items(), key=lambda x: x[1]['rate'], reverse=True)
    native_leak.rate_dict = pss_dict
    info = '各类型内存占比如下:'
    for key, value in sorted_pss_dict:
        info += f'{key.value}内存占用：{value["pss"] / 1024:.2f}MB，占比：{value["rate"] * 100:.2f}%\n'
    return info


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-p", "--path", required=True, help="文件路径")
    args = parser.parse_args()
    with open(args.path, 'r', encoding='utf-8', errors='ignore') as file:
        context_ = file.readlines()
        native_leak_ = NativeLeak().build(context_)
    sample_path_ = args.path.replace('.txt', '.pkl').replace('smaps', 'sample')
    rate_info = get_rate_info(native_leak_, sample_path_)
    native_obj_path = args.path.replace('.txt', '.pkl')
    with open(native_obj_path, 'wb') as f:
        dill.dump(native_leak_, f)
    print(rate_info)
